### PR TITLE
Add prettier pre-commit hook for md files

### LINKED ISSUE #18: [DOCS] Add prettier integration for .github files
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

Add a pre-commit hook to run prettier on all Markdown files for the .github repo. This could be used as a template for other repos as well.

### Motivation

After receiving a PR based on the CoronaTracker instructions (bump version, run `yarn lint`, etc), the submitted code had some key formatting differences based on Prettier's standards for Markdown files.

The changes were minor, i.e.:
- `__` was replaced with `**`
- spacing adjusted on new lines

However, since we are using Prettier with CoronaTracker, it makes sense to me to make this a standard across the board, and it might eliminate future syntax issues as others submit future PRs.

### Possible Alternatives

Leave things as-is, the current code will display correctly and follows current standards, but there are slight variations in how one author might do it compared to another, i.e. the formatting of bold text listed above.

### Additional Context

I believe this would add the requirement that Yarn is installed in order to submit changes, and relevant documentation would need to be updated. 

This also makes the case for separating CoronaTracker docs from the .github repo for pull requests, as the instructions would vary slightly, and this template could be applied to all other repos as well for consistency.

Questions
- is this worth the extra effort / steps?
- how will this affect other repos?
- should this focus only on Markdown files? i.e. `*.md`

### PR DESCRIPTION
**Pull request by whoabuddy**
# ⚠️ __IMPORTANT: Please do not create a Pull Request without creating an issue first.__

All changes need to be discussed before proceeding. Failure to do so may result in the pull request being rejected.

Please be sure to review our [Code of Conduct](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md), [Contributing Guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md), and [Support documentation](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) before submitting a pull request.

-----

## Please include the issue number the pull request fixes by replacing YOUR-ISSUE-HERE in the text below.

Fixes #18 

## Summary

Adds `pre-commit` hook for `pretty-quick` that processes `*.md`.

## Details

This creates a consisten format for all markdown documentation files and can be utilized as a template for all other CoronaTracker repos except the CoronaTracker software, which has slightly varied instructions.

## Test Plan (required)

To set this up, I had to do the following:

**Install `nvm`, `node`, and `yarn`:**

```
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
nvm install node
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
```

**Add an alias for node in `~/.bashrc` based on Yarn docs:**

```
# alias for yarn and nvm
alias node=nodejs
```

**Set up yarn in the repo and add dependencies**

```
yarn
yarn add prettier --dev --exact
yarn add pretty-quick husky --dev
```

**Update `package.json` with pre-commit hook:**

```
{
  "devDependencies": {
    "husky": "^4.2.5",
    "prettier": "2.0.5",
    "pretty-quick": "^2.0.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged --pattern \"*.md\""
    }
  }
```

**Tested by modifying all markdown files:**

All markdown files in the repo were updated to include a small change, which resulted in the pre-commit hook running and formatting the files before they are submitted.

## Final Checklist

- [x] Did you add any new tests as necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits? _(can be done at merge)_
- [x] Did you use `yarn` not `npm`? _(important!)_
- [x] Did you format the code with prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by whoabuddy** [comment]
I see `836 files` changed - is there a way I can avoid so many extra files for this one feature, or is that typical of node/yarn?

**Comment by acthelemann** [comment]
Add a `.gitignore` file with a line:

```plain
node_modules/
```

**Comment by whoabuddy** [comment]
Putting this for reference, after adding the line to `.gitignore` I also had to remove the files that should be ignored from the repo. It was much simpler than I thought. [Article from 2014.](https://eric.blog/2014/05/11/remove-files-from-git-addingupdating-gitignore/)

```
git rm -r --cached .
git add -A
git commit -am "remove ignored files"
```

@acthelemann or @SomeMoosery - do you see any other issues with merging?

**Review by acthelemann — APPROVED** [review]
Looks good to me!

**Review by SomeMoosery — APPROVED** [review]
LGTM as well! great work as always

**Pull request merged**
